import { getCatalog, send, isConnected } from './api.js';
const state={data:null,cart:new Map(),activeCategory:'todos',adminCategory:'todos',adminToken:localStorage.getItem('fares-glam-admin-token')||''};
const $=selector=>document.querySelector(selector);
const money=value=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(value||0);
const imagePath=product=>product.imagen_drive_id?`https://lh3.googleusercontent.com/d/${product.imagen_drive_id}=w800`:product.imagen_repo||'assets/branding/logo-redondo.png';
const sold=product=>product.agotado||product.stock<=0;
const SEP='||';
const colorsOf=p=>Array.isArray(p&&p.colores)?p.colores:String((p&&p.colores)||'').split(',').map(c=>c.trim()).filter(Boolean);
const keyId=key=>String(key).split(SEP)[0];
const keyColor=key=>String(key).split(SEP)[1]||'';
const cartKey=(id,color)=>color?id+SEP+color:id;
const qtyOf=id=>[...state.cart].reduce((sum,[key,qty])=>keyId(key)===id?sum+qty:sum,0);
const productById=id=>state.data.productos.find(item=>item.id===id);
const cartTotal=()=>[...state.cart].reduce((sum,[key,qty])=>sum+(productById(keyId(key))?.precio||0)*qty,0);
function sanitizeCart(){for(const key of [...state.cart.keys()]){const p=productById(keyId(key));const colors=p?colorsOf(p):[];const color=keyColor(key);if(!p||(colors.length&&!colors.includes(color))||(!colors.length&&color))state.cart.delete(key)}persistCart()}
const isNew=product=>product.creado_en&&Date.now()-new Date(product.creado_en).getTime()<5*24*60*60*1000;
async function boot(){try{state.data=await getCatalog();sanitizeCart();renderNav();renderCatalog();updateCart();}catch(error){$('#catalog').innerHTML=`<div class="loading">No pudimos cargar la colección. ${error.message}</div>`}route();window.addEventListener('hashchange',route)}
function renderNav(){const nav=$('#category-nav');nav.innerHTML='<button class="chip active" data-category="todos">Todo</button>'+state.data.categorias.filter(c=>c.visible!==false).sort((a,b)=>a.orden-b.orden).map(c=>`<button class="chip" data-category="${c.slug}">${c.nombre}</button>`).join('');nav.onclick=event=>{const button=event.target.closest('[data-category]');if(!button)return;state.activeCategory=button.dataset.category;document.querySelectorAll('.chip').forEach(chip=>chip.classList.toggle('active',chip===button));renderCatalog()}}
function renderCatalog(){const products=state.data.productos.filter(p=>p.visible!==false);const groups=state.data.categorias.filter(c=>c.visible!==false&& (state.activeCategory==='todos'||c.slug===state.activeCategory)).sort((a,b)=>a.orden-b.orden);$('#catalog').innerHTML=groups.map(category=>{const items=products.filter(p=>p.categoria===category.slug).sort((a,b)=>Number(a.agotado)-Number(b.agotado)||a.orden-b.orden);if(!items.length)return '';return `<section class="category-section" id="${category.slug}"><h2 class="category-title">${category.nombre}</h2><div class="product-grid">${items.map(productCard).join('')}</div></section>`}).join('')||'<div class="loading">No hay productos en esta categoría.</div>';$('#catalog').onclick=handleCatalogClick}
function productCard(p){const quantity=qtyOf(p.id);const unavailable=sold(p);const colors=colorsOf(p);const colorsLine=colors.length&&!sold(p)?`<span class="colors-line">Colores: ${escapeHtml(colors.join(', '))}</span>`:'';const availability=p.stock>0?`<span class="availability">${p.stock} disponibles</span>`:'';const hasDiscount=Number(p.precio_anterior)>Number(p.precio);const discount=hasDiscount?Math.round((1-p.precio/p.precio_anterior)*100):0;const price=hasDiscount?`<p class="price"><s>${money(p.precio_anterior)}</s><strong>${money(p.precio)}</strong>${p.precio_por_unidad?'<small> c/u</small>':''}</p>`:`<p class="price">${money(p.precio)}${p.precio_por_unidad?'<small> c/u</small>':''}</p>`;return `<article class="product-card ${unavailable?'sold':''}" data-id="${p.id}"><div class="product-photo"><img src="${imagePath(p)}" alt="${escapeHtml(p.nombre)}" loading="lazy" decoding="async"><span class="new-label" ${isNew(p)?'':'hidden'}>NEW</span><span class="discount-label" ${hasDiscount?'':'hidden'}>-${discount}%</span><span class="sold-label" ${unavailable?'':'hidden'}>Agotado</span></div><div class="product-info"><h3 class="product-name">${escapeHtml(p.nombre)}</h3><p class="finish">${escapeHtml(p.acabado||'')}</p>${price}${availability}${colorsLine}${unavailable?'<button class="add" disabled>Agotado</button>':quantity?`<div class="quantity"><button data-action="minus" aria-label="Quitar una unidad">−</button><span>${quantity}</span><button data-action="plus" aria-label="Agregar una unidad" ${quantity>=p.stock?'disabled':''}>+</button></div>`:'<button class="add" data-action="add">Agregar</button>'}</div></article>`}
function addUnit(id,color){const product=productById(id);if(!product||qtyOf(id)>=product.stock)return;const key=cartKey(id,color);state.cart.set(key,(state.cart.get(key)||0)+1);persistCart();renderCatalog();updateCart()}
function removeUnit(id){const keys=[...state.cart.keys()].filter(key=>keyId(key)===id);const key=keys[keys.length-1];if(!key)return;const qty=state.cart.get(key);if(qty<=1)state.cart.delete(key);else state.cart.set(key,qty-1);persistCart();renderCatalog();updateCart()}
function askColor(product){$('#color-title').textContent=product.nombre;$('#color-options').innerHTML=colorsOf(product).map(color=>`<button type="button" class="color-option" data-color="${escapeHtml(color)}">${escapeHtml(color)}</button>`).join('');$('#color-dialog').dataset.productId=product.id;$('#color-dialog').showModal()}
function handleColorClick(event){const button=event.target.closest('[data-color]');if(!button)return;const id=$('#color-dialog').dataset.productId;$('#color-dialog').close();addUnit(id,button.dataset.color)}
function handleCatalogClick(event){const action=event.target.closest('[data-action]')?.dataset.action;if(!action)return;const card=event.target.closest('[data-id]');const id=card.dataset.id;const product=productById(id);if(action==='add'||action==='plus'){if(colorsOf(product).length)askColor(product);else addUnit(id,'')}if(action==='minus')removeUnit(id)}
function persistCart(){localStorage.setItem('fares-glam-cart',JSON.stringify([...state.cart]))}
function restoreCart(){try{state.cart=new Map(JSON.parse(localStorage.getItem('fares-glam-cart')||'[]'))}catch(error){state.cart=new Map()}}
function updateCart(){const count=[...state.cart.values()].reduce((sum,value)=>sum+value,0);const total=cartTotal();const admin=location.hash.toLowerCase()==='#admin';$('#cart-bar').hidden=admin||count===0;$('#cart-bar').style.display=admin?'none':'';$('#cart-count').textContent=count;$('#cart-total').textContent=money(total)}
function openCart(){const lines=[...state.cart].map(([key,qty])=>{const id=keyId(key),color=keyColor(key);const p=productById(id);return `<div class="cart-line" data-line-id="${escapeHtml(key)}"><img class="cart-thumb" src="${imagePath(p)}" alt=""><div class="cart-line-info"><strong>${escapeHtml(p.nombre)}</strong>${color?`<span class="cart-color">Color: ${escapeHtml(color)}</span>`:''}<small>${money(p.precio)} · ${money(p.precio*qty)}</small></div><div class="line-controls"><button data-line="minus" aria-label="Quitar una unidad">−</button><span>${qty}</span><button data-line="plus" aria-label="Agregar una unidad" ${qtyOf(id)>=p.stock?'disabled':''}>+</button></div><button class="line-remove" data-line="remove" aria-label="Quitar producto">×</button></div>`}).join('')||'<p class="form-note">Aún no has agregado productos.</p>';$('#cart-lines').innerHTML=lines;$('#dialog-total').textContent=money(cartTotal());$('#cart-dialog').showModal()}
function handleCartClick(event){const action=event.target.closest('[data-line]')?.dataset.line;if(!action)return;const key=event.target.closest('[data-line-id]').dataset.lineId;const id=keyId(key);const p=productById(id);const qty=state.cart.get(key)||0;if(action==='plus'&&qtyOf(id)<p.stock)state.cart.set(key,qty+1);if(action==='minus'){if(qty<=1)state.cart.delete(key);else state.cart.set(key,qty-1)}if(action==='remove')state.cart.delete(key);persistCart();openCart();renderCatalog();updateCart()}
const PAYMENT={nequi:'3044160047',llave:'3044160047'};
const DEFAULT_WA_TEMPLATE='Hola {nombre}, te escribimos de {tienda}.\n\nTu pedido {pedido} fue registrado:\n{lineas}\n\nTotal: {total}\n\nDirección: {direccion}\nPunto de referencia: {referencia}\n\nPara pagar tu pedido:\nNequi: 3044160047\n🔑 Llave: 3044160047\n\nCuando realices el pago, envíanos el comprobante por este chat. ¡Gracias!';
function showOrderConfirmation(o){const lines=o.summary.map(l=>`<li><span>${l.cantidad} × ${escapeHtml(l.nombre)}</span><b>${money(l.subtotal)}</b></li>`).join('');$('#confirm-content').innerHTML=`<span class="eyebrow">${o.pedido?'Pedido '+escapeHtml(o.pedido):'Confirmación'}</span><h2>Pedido realizado</h2><p class="confirm-lead">Gracias, ${escapeHtml(o.nombre)}. Te enviaremos la confirmación de tu pedido por WhatsApp.</p><ul class="confirm-lines">${lines}</ul><div class="confirm-total"><span>Total</span><strong>${money(o.total)}</strong></div><div class="confirm-block"><small>Entrega</small><p>${escapeHtml(o.direccion)}<br>${escapeHtml(o.referencia)}</p></div><div class="confirm-pay"><small>Para pagar tu pedido</small><p><span>Nequi</span><b>${PAYMENT.nequi}</b></p><p><span>🔑 Llave</span><b>${PAYMENT.llave}</b></p></div><button class="button primary full" type="button" data-confirm-done>Entendido</button>`;$('#confirm-dialog').showModal()}
async function submitOrder(event){event.preventDefault();const form=new FormData(event.target);const items=[...state.cart].map(([key,cantidad])=>({id:keyId(key),cantidad,color:keyColor(key)}));const summary=[...state.cart].map(([key,qty])=>{const p=productById(keyId(key));const color=keyColor(key);return{nombre:(p?p.nombre:keyId(key))+(color?` (${color})`:''),cantidad:qty,subtotal:(p?p.precio:0)*qty}});const nombre=String(form.get('nombre')||'').trim(),direccion=String(form.get('direccion')||'').trim(),referencia=String(form.get('referencia')||'').trim();const response=await send('order_create',{request_id:crypto.randomUUID(),nombre,whatsapp:form.get('whatsapp'),direccion,referencia,items});if(response.ok){state.data.productos=state.data.productos.map(product=>{const used=items.filter(line=>line.id===product.id).reduce((t,line)=>t+line.cantidad,0);return used?{...product,stock:Math.max(0,product.stock-used)}:product});state.cart.clear();persistCart();$('#cart-dialog').close();updateCart();renderCatalog();showOrderConfirmation({pedido:response.pedido,nombre,direccion,referencia,summary,total:response.total??summary.reduce((t,l)=>t+l.subtotal,0)})}else if(response.code==='DEMO'){showMessage('<h2>Pedido listo</h2><p>El catálogo está en modo demo. Conecta el Apps Script en <strong>js/config.js</strong> para recibir pedidos reales.</p>')}else showMessage(`<h2>No pudimos enviar el pedido</h2><p>${escapeHtml(response.message||'Revisa los datos e inténtalo de nuevo.')}</p>`)}
function showMessage(html){$('#message-content').innerHTML=html;$('#message-dialog').showModal()}
async function route(){const admin=location.hash.toLowerCase()==='#admin';$('#store-view').hidden=admin;$('.site-footer').hidden=admin;$('#admin-view').hidden=!admin;$('#cart-bar').hidden=admin||state.cart.size===0;$('#cart-bar').style.display=admin?'none':'';if(admin)renderAdmin()}
function renderAdmin(){const root=$('#admin-root');if(!state.adminToken){root.innerHTML=`<div class="admin-card"><span class="eyebrow">Acceso</span><h2>Entra a tu catálogo</h2><p>Usa tu PIN para continuar.</p><form id="admin-login"><label class="simple-label">PIN<input name="pin" type="password" inputmode="numeric" maxlength="4" required></label><button class="button primary">Entrar</button></form></div>`;$('#admin-login').onsubmit=async event=>{event.preventDefault();const pin=new FormData(event.target).get('pin');const response=await send('login',{pin});if(response.ok){state.adminToken=response.token;localStorage.setItem('fares-glam-admin-token',response.token);renderAdmin()}else showMessage(`<h2>Acceso no disponible</h2><p>${escapeHtml(response.message)}</p>`)}}else{state.adminData=null;state.adminView='products';root.innerHTML=`<div class="admin-actions"><button class="button primary" data-admin-action="new">+ Nuevo producto</button><button class="button" data-admin-action="orders">Pedidos</button></div><div id="admin-content" class="admin-card"><p>Cargando panel...</p></div>`;loadAdminData()}}
async function loadAdminData(view){const response=await send('admin_data',{token:state.adminToken});if(!response.ok){state.adminToken='';localStorage.removeItem('fares-glam-admin-token');renderAdmin();return}state.adminData=response;state.adminProducts=response.productos;if(view==='orders'||state.adminView==='orders'){renderAdminOrders();return}renderAdminProducts()}
function renderAdminProducts(){const response=state.adminData;state.adminView='products';markNewOrders(response);setAdminButtons();$('#admin-content').innerHTML=`<div class="admin-summary"><strong>${response.productos.length} productos</strong><span>${response.pedidos.length} pedidos</span></div><div class="admin-create" id="admin-create" hidden><h2>Nuevo producto</h2><form id="new-product-form"><label>Foto<input name="foto" type="file" accept="image/jpeg,image/png,image/webp"></label><label>Categoría<select name="categoria" required>${response.categorias.filter(c=>c.visible!==false).map(c=>`<option value="${c.slug}">${escapeHtml(c.nombre)}</option>`).join('')}</select></label><button class="text-button" type="button" data-admin-action="category">+ Nueva categoría</button><div id="new-category-box" hidden><label>Nombre de categoría<input name="nueva_categoria"></label><button type="button" class="button" data-admin-action="save-category">Guardar categoría</button></div><label>Nombre<input name="nombre" required></label><label>Acabado<input name="acabado"></label><label class="colors-field">Colores disponibles (opcional)<input name="colores" placeholder="Ej: Rojo, Verde, Azul"><small>Sepáralos con coma. Déjalo vacío si no aplica.</small></label><label>Precio<input name="precio" type="number" min="0" required></label><label>Stock inicial<input name="stock" type="number" min="0" value="0" required></label><button class="button primary" type="submit">Crear producto</button></form></div><div class="admin-category-filter"><button class="active" data-admin-category="todos">Todos</button>${response.categorias.filter(c=>c.visible!==false).sort((a,b)=>a.orden-b.orden).map(c=>`<button data-admin-category="${c.slug}">${escapeHtml(c.nombre)}</button>`).join('')}</div><h2 class="admin-section-title">Productos</h2><div id="admin-product-list" class="admin-product-list"></div>`;renderAdminProductList();$('#new-product-form').onsubmit=event=>{event.preventDefault();createProduct(event.target)}}
function renderAdminProductList(){const list=$('#admin-product-list');if(!list)return;const products=state.adminProducts.filter(p=>state.adminCategory==='todos'||p.categoria===state.adminCategory).sort((a,b)=>{const soldOrder=Number(sold(a))-Number(sold(b));if(soldOrder)return soldOrder;return String(b.actualizado||'').localeCompare(String(a.actualizado||''))});list.innerHTML=products.map(adminProductCard).join('')||'<p class="form-note">No hay productos en esta categoría.</p>'}
function setAdminButtons(){const orders=document.querySelector('[data-admin-action="orders"]');if(orders)orders.classList.toggle('active',state.adminView==='orders');const create=$('#admin-create');const add=document.querySelector('[data-admin-action="new"]');if(add)add.classList.toggle('active',state.adminView==='products'&&!!create&&!create.hidden)}
function markNewOrders(data){const button=document.querySelector('[data-admin-action="orders"]');if(button&&data)button.innerHTML=`Pedidos${(data.pedidos||[]).some(order=>order.estado==='nuevo')?' <span class="new-tag">NEW</span>':''}`;}
function renderAdminOrders(){const orders=state.adminData?.pedidos||[];state.adminView='orders';markNewOrders(state.adminData);setAdminButtons();$('#admin-content').innerHTML=`<div class="admin-summary"><strong>Pedidos</strong><span>${orders.length} registrados</span></div><div class="admin-orders">${orders.map(order=>`<article class="admin-order" data-order-id="${order.id_pedido}"><div><strong>${escapeHtml(order.id_pedido)} · ${escapeHtml(order.nombre)}</strong><small>${escapeHtml(order.whatsapp)} · ${escapeHtml(order.fecha)}</small><p>${escapeHtml(order.resumen||'')}</p>${order.direccion?`<p class="order-address">${escapeHtml(order.direccion)}${order.referencia?' · '+escapeHtml(order.referencia):''}</p>`:''}<b>${money(order.total)}</b></div><div class="order-update"><a class="button primary contact-button" data-order-contact href="${whatsappOrderUrl(order)}" target="_blank" rel="noreferrer">Contactar</a><select data-order-status><option value="nuevo" ${order.estado==='nuevo'?'selected':''}>Nuevo</option><option value="contactado" ${order.estado==='contactado'?'selected':''}>Contactado</option><option value="entregado" ${order.estado==='entregado'?'selected':''}>Entregado</option><option value="cancelado" ${order.estado==='cancelado'?'selected':''}>Cancelado</option></select><button class="button" data-order-save>Guardar estado</button></div></article>`).join('')||'<p class="form-note">Todavía no hay pedidos.</p>'}`}
function whatsappOrderUrl(order){const number=String(order.whatsapp||'').replace(/\D/g,'').replace(/^57/,'');const stored=state.adminData?.config?.plantilla_whatsapp;const template=stored&&String(stored).includes('{direccion}')?String(stored):DEFAULT_WA_TEMPLATE;const message=template.replaceAll('{nombre}',String(order.nombre||'')).replaceAll('{tienda}',String(state.adminData?.config?.nombre_tienda||'Fares Glam')).replaceAll('{pedido}',String(order.id_pedido||'')).replaceAll('{direccion}',String(order.direccion||'')).replaceAll('{referencia}',String(order.referencia||'')).replaceAll('{lineas}',String(order.resumen||'')).replaceAll('{total}',money(order.total));return `https://wa.me/57${number}?text=${encodeURIComponent(message)}`}
function adminProductCard(p){return `<article class="admin-product" data-admin-id="${p.id}"><div class="admin-product-image"><img src="${imagePath(p)}" alt="${escapeHtml(p.nombre)}" loading="lazy"><button class="delete-product" data-admin-delete aria-label="Eliminar ${escapeHtml(p.nombre)}" title="Eliminar producto">×</button></div><div class="admin-product-fields"><strong>${escapeHtml(p.id)}</strong><label>Nombre<input data-field="nombre" value="${escapeHtml(p.nombre)}"></label><label>Precio<input data-field="precio" type="number" min="0" value="${Number(p.precio)||0}"></label><label>Stock<input data-field="stock" type="number" min="0" value="${Number(p.stock)||0}"></label><label class="colors-field">Colores (opcional, separados por coma)<input data-field="colores" placeholder="Ej: Rojo, Verde, Azul" value="${escapeHtml(colorsOf(p).join(', '))}"></label><label class="check-field"><input data-field="agotado_manual" type="checkbox" ${p.agotado_manual?'checked':''}> Agotado manual</label><label class="check-field"><input data-field="visible" type="checkbox" ${p.visible!==false?'checked':''}> Mostrar</label><label class="file-button">Cambiar foto<input data-admin-image type="file" accept="image/jpeg,image/png,image/webp" hidden></label><button class="button primary" data-admin-save>Guardar</button></div></article>`}
async function createProduct(form){const data=new FormData(form);const response=await send('product_create',{token:state.adminToken,categoria:data.get('categoria'),nombre:data.get('nombre'),acabado:data.get('acabado'),colores:data.get('colores'),precio:data.get('precio'),stock:data.get('stock')});if(!response.ok){showMessage(`<h2>No se creó</h2><p>${escapeHtml(response.message)}</p>`);return}const file=data.get('foto');if(file&&file.size){await uploadAdminImage({dataset:{adminId:response.producto.id},querySelector:()=>null},file)}showMessage('<h2>Producto creado</h2><p>Ya aparece en tu catálogo.</p>');loadAdminData()}
async function createCategory(){const input=$('#new-category-box input');const response=await send('category_create',{token:state.adminToken,nombre:input.value});if(response.ok){showMessage('<h2>Categoría creada</h2><p>Ya está disponible para nuevos productos.</p>');loadAdminData()}else showMessage(`<h2>No se creó</h2><p>${escapeHtml(response.message)}</p>`)}
function readDataUrl(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)})}
async function uploadAdminImage(row,file){if(!file)return;if(file.size>4*1024*1024){showMessage('<h2>Imagen muy pesada</h2><p>La imagen debe pesar menos de 4 MB.</p>');return}const response=await send('image_upload',{token:state.adminToken,id:row.dataset.adminId,mime:file.type,data:await readDataUrl(file)});if(response.ok){showMessage('<h2>Foto actualizada</h2><p>La imagen ya quedó guardada en Drive.</p>');loadAdminData()}else showMessage(`<h2>No se subió</h2><p>${escapeHtml(response.message||'Revisa la conexión.')}</p>`)}
async function saveAdminProduct(row){const fields={};row.querySelectorAll('[data-field]').forEach(input=>{fields[input.dataset.field]=input.type==='checkbox'?input.checked:input.value});const response=await send('product_patch',{token:state.adminToken,id:row.dataset.adminId,...fields});if(response.ok){const i=state.adminProducts.findIndex(x=>x.id===row.dataset.adminId);if(i>=0&&response.producto)state.adminProducts[i]=response.producto;showMessage('<h2>Guardado</h2><p>El producto se actualizó correctamente.</p>')}else showMessage(`<h2>No se guardó</h2><p>${escapeHtml(response.message||'Revisa la conexión.')}</p>`)}
async function deleteAdminProduct(row){const product=state.adminProducts.find(item=>item.id===row.dataset.adminId);if(!product||!window.confirm(`¿Eliminar definitivamente ${product.nombre}? Esta acción no se puede deshacer.`))return;const response=await send('product_delete',{token:state.adminToken,id:product.id});if(response.ok){showMessage('<h2>Producto eliminado</h2><p>Se quitó de la tienda, el Sheet y Drive.</p>');loadAdminData()}else showMessage(`<h2>No se eliminó</h2><p>${escapeHtml(response.message||'Revisa la conexión.')}</p>`)}
async function saveAdminOrder(row){const status=row.querySelector('[data-order-status]').value;const response=await send('order_update',{token:state.adminToken,id_pedido:row.dataset.orderId,estado:status});if(response.ok){showMessage('<h2>Pedido actualizado</h2><p>El estado quedó guardado.</p>');loadAdminData('orders')}else showMessage(`<h2>No se actualizó</h2><p>${escapeHtml(response.message||'Revisa la conexión.')}</p>`)}
async function migrateImagesToDrive(){if(!isConnected){showMessage('<h2>Falta conectar Apps Script</h2><p>Primero coloca la URL terminada en /exec dentro de js/config.js.</p>');return}const products=state.adminProducts||[];let done=0;showMessage('<h2>Subiendo fotos...</h2><p>La ventana puede tardar unos minutos. No la cierres.</p>');for(const product of products){if(product.imagen_drive_id)continue;try{const response=await fetch('./'+product.imagen_repo);const blob=await response.blob();const result=await send('image_upload',{token:state.adminToken,id:product.id,mime:blob.type||'image/jpeg',data:await readDataUrl(blob)});if(result.ok)done++}catch(error){}}showMessage(`<h2>Fotos migradas</h2><p>${done} imágenes quedaron en Drive y vinculadas al catálogo.</p>`);loadAdminData()}
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
$('#confirm-dialog').addEventListener('cancel',e=>e.preventDefault());$('#confirm-content').onclick=e=>{if(e.target.closest('[data-confirm-done]'))$('#confirm-dialog').close()};$('#open-cart').onclick=openCart;$('#color-options').onclick=handleColorClick;$('#cart-lines').onclick=handleCartClick;$('#order-form').onsubmit=submitOrder;document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>button.closest('dialog').close());$('#admin-root').onclick=event=>{const action=event.target.closest('[data-admin-action]')?.dataset.adminAction;if(action==='orders'){if(!state.adminData){state.adminView=state.adminView==='orders'?'products':'orders';setAdminButtons();return}if(state.adminView==='orders')renderAdminProducts();else renderAdminOrders();return}if(action==='new'&&!state.adminData)return;if(action==='new'){const wasOrders=state.adminView==='orders';if(wasOrders){renderAdminProducts();$('#admin-create').hidden=false}else{$('#admin-create').hidden=!$('#admin-create').hidden}setAdminButtons();if(!$('#admin-create').hidden)$('#admin-create').scrollIntoView({behavior:'smooth',block:'start'});return}if(action==='category')$('#new-category-box').hidden=!$('#new-category-box').hidden;if(action==='save-category')createCategory();if(event.target.matches('[data-admin-category]')){state.adminCategory=event.target.dataset.adminCategory;document.querySelectorAll('[data-admin-category]').forEach(button=>button.classList.toggle('active',button===event.target));renderAdminProductList()}if(event.target.matches('[data-admin-save]'))saveAdminProduct(event.target.closest('[data-admin-id]'));if(event.target.matches('[data-admin-delete]'))deleteAdminProduct(event.target.closest('[data-admin-id]'));if(event.target.matches('[data-order-save]'))saveAdminOrder(event.target.closest('[data-order-id]'));if(event.target.matches('[data-order-contact]'))send('order_update',{token:state.adminToken,id_pedido:event.target.closest('[data-order-id]').dataset.orderId,estado:'contactado'})};$('#admin-root').onchange=event=>{if(event.target.matches('[data-admin-image]'))uploadAdminImage(event.target.closest('[data-admin-id]'),event.target.files[0])};restoreCart();boot();
