import { getCatalog, send, isConnected } from './api.js';
const state={data:null,cart:new Map(),activeCategory:'todos',adminToken:localStorage.getItem('fares-glam-admin-token')||''};
const $=selector=>document.querySelector(selector);
const money=value=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(value||0);
const imagePath=product=>product.imagen_drive_id?`https://lh3.googleusercontent.com/d/${product.imagen_drive_id}=w800`:product.imagen_repo||'assets/branding/logo-redondo.png';
const sold=product=>product.agotado||product.stock<=0;
async function boot(){try{state.data=await getCatalog();renderNav();renderCatalog();updateCart();}catch(error){$('#catalog').innerHTML=`<div class="loading">No pudimos cargar la colección. ${error.message}</div>`}route();window.addEventListener('hashchange',route)}
function renderNav(){const nav=$('#category-nav');nav.innerHTML='<button class="chip active" data-category="todos">Todo</button>'+state.data.categorias.filter(c=>c.visible!==false).sort((a,b)=>a.orden-b.orden).map(c=>`<button class="chip" data-category="${c.slug}">${c.nombre}</button>`).join('');nav.onclick=event=>{const button=event.target.closest('[data-category]');if(!button)return;state.activeCategory=button.dataset.category;document.querySelectorAll('.chip').forEach(chip=>chip.classList.toggle('active',chip===button));renderCatalog()}}
function renderCatalog(){const products=state.data.productos.filter(p=>p.visible!==false);const groups=state.data.categorias.filter(c=>c.visible!==false&& (state.activeCategory==='todos'||c.slug===state.activeCategory)).sort((a,b)=>a.orden-b.orden);$('#catalog').innerHTML=groups.map(category=>{const items=products.filter(p=>p.categoria===category.slug).sort((a,b)=>Number(a.agotado)-Number(b.agotado)||a.orden-b.orden);if(!items.length)return '';return `<section class="category-section" id="${category.slug}"><h2 class="category-title">${category.nombre}</h2><div class="product-grid">${items.map(productCard).join('')}</div></section>`}).join('')||'<div class="loading">No hay productos en esta categoría.</div>';$('#catalog').onclick=handleCatalogClick}
function productCard(p){const quantity=state.cart.get(p.id)||0;const unavailable=sold(p);return `<article class="product-card ${unavailable?'sold':''}" data-id="${p.id}"><div class="product-photo"><img src="${imagePath(p)}" alt="${escapeHtml(p.nombre)}" loading="lazy" decoding="async"><span class="sold-label" ${unavailable?'':'hidden'}>Agotado</span></div><div class="product-info"><h3 class="product-name">${escapeHtml(p.nombre)}</h3><p class="finish">${escapeHtml(p.acabado||'')}</p><p class="price">${money(p.precio)}${p.precio_por_unidad?'<small> c/u</small>':''}</p>${unavailable?'<button class="add" disabled>Agotado</button>':quantity?`<div class="quantity"><button data-action="minus" aria-label="Quitar una unidad">−</button><span>${quantity}</span><button data-action="plus" aria-label="Agregar una unidad" ${quantity>=p.stock?'disabled':''}>+</button></div>`:'<button class="add" data-action="add">Agregar</button>'}</div></article>`}
function handleCatalogClick(event){const action=event.target.closest('[data-action]')?.dataset.action;if(!action)return;const card=event.target.closest('[data-id]');const id=card.dataset.id;const product=state.data.productos.find(item=>item.id===id);const quantity=state.cart.get(id)||0;if(action==='add'||action==='plus')state.cart.set(id,Math.min(product.stock,quantity+1));if(action==='minus'){if(quantity<=1)state.cart.delete(id);else state.cart.set(id,quantity-1)}persistCart();renderCatalog();updateCart()}
function persistCart(){localStorage.setItem('fares-glam-cart',JSON.stringify([...state.cart]))}
function restoreCart(){try{state.cart=new Map(JSON.parse(localStorage.getItem('fares-glam-cart')||'[]'))}catch(error){state.cart=new Map()}}
function updateCart(){const count=[...state.cart.values()].reduce((sum,value)=>sum+value,0);const total=[...state.cart].reduce((sum,[id,qty])=>sum+(state.data.productos.find(p=>p.id===id)?.precio||0)*qty,0);$('#cart-bar').hidden=count===0;$('#cart-count').textContent=`${count} ${count===1?'producto':'productos'}`;$('#cart-total').textContent=money(total)}
function openCart(){const lines=[...state.cart].map(([id,qty])=>{const p=state.data.productos.find(item=>item.id===id);return `<div class="cart-line" data-line-id="${id}"><div>${escapeHtml(p.nombre)}<small>${money(p.precio)} · ${money(p.precio*qty)}</small></div><div class="line-controls"><button data-line="minus">−</button><span>${qty}</span><button data-line="plus" ${qty>=p.stock?'disabled':''}>+</button></div><button class="close" data-line="remove" aria-label="Quitar">×</button></div>`}).join('')||'<p class="form-note">Aún no has agregado productos.</p>';$('#cart-lines').innerHTML=lines;const total=[...state.cart].reduce((sum,[id,qty])=>sum+(state.data.productos.find(p=>p.id===id)?.precio||0)*qty,0);$('#dialog-total').textContent=money(total);$('#cart-dialog').showModal()}
function handleCartClick(event){const action=event.target.closest('[data-line]')?.dataset.line;if(!action)return;const id=event.target.closest('[data-line-id]').dataset.lineId;const p=state.data.productos.find(item=>item.id===id);const qty=state.cart.get(id)||0;if(action==='plus')state.cart.set(id,Math.min(p.stock,qty+1));if(action==='minus'){if(qty<=1)state.cart.delete(id);else state.cart.set(id,qty-1)}if(action==='remove')state.cart.delete(id);persistCart();openCart();renderCatalog();updateCart()}
async function submitOrder(event){event.preventDefault();const form=new FormData(event.target);const items=[...state.cart].map(([id,cantidad])=>({id,cantidad}));const response=await send('order_create',{request_id:crypto.randomUUID(),nombre:form.get('nombre'),whatsapp:form.get('whatsapp'),items});if(response.ok){state.cart.clear();persistCart();$('#cart-dialog').close();updateCart();showMessage(`<h2>¡Gracias, ${escapeHtml(form.get('nombre'))}!</h2><p>Recibimos tu pedido <strong>${response.pedido||''}</strong>. Te escribiremos por WhatsApp para coordinar el envío.</p>`);if(isConnected)state.data=await getCatalog();renderCatalog()}else if(response.code==='DEMO'){showMessage('<h2>Pedido listo</h2><p>El catálogo está en modo demo. Conecta el Apps Script en <strong>js/config.js</strong> para recibir pedidos reales.</p>')}else showMessage(`<h2>No pudimos enviar el pedido</h2><p>${escapeHtml(response.message||'Revisa los datos e inténtalo de nuevo.')}</p>`)}
function showMessage(html){$('#message-content').innerHTML=html;$('#message-dialog').showModal()}
async function route(){const admin=location.hash.toLowerCase()==='#admin';$('#store-view').hidden=admin;$('.site-footer').hidden=admin;$('#admin-view').hidden=!admin;if(admin)renderAdmin()}
function renderAdmin(){const root=$('#admin-root');if(!state.adminToken){root.innerHTML=`<div class="admin-card"><span class="eyebrow">Acceso</span><h2>Entra a tu catálogo</h2><p>Usa el PIN configurado en Apps Script para administrar productos y pedidos.</p><form id="admin-login"><input name="pin" type="password" inputmode="numeric" maxlength="4" placeholder="PIN de 4 dígitos" required><button class="button primary">Entrar</button></form><p class="form-note">En modo demo, conecta primero la URL del Apps Script.</p></div>`;$('#admin-login').onsubmit=async event=>{event.preventDefault();const pin=new FormData(event.target).get('pin');const response=await send('login',{pin});if(response.ok){state.adminToken=response.token;localStorage.setItem('fares-glam-admin-token',response.token);renderAdmin()}else showMessage(`<h2>Acceso no disponible</h2><p>${escapeHtml(response.message)}</p>`)}}else{root.innerHTML=`<div class="admin-actions"><button class="button primary" data-admin-action="data">Actualizar datos</button><button class="button" data-admin-action="logout">Salir</button></div><div id="admin-content" class="admin-card"><p>Cargando panel...</p></div>`;loadAdminData()}}
async function loadAdminData(){const response=await send('admin_data',{token:state.adminToken});if(!response.ok){state.adminToken='';localStorage.removeItem('fares-glam-admin-token');renderAdmin();return}state.adminProducts=response.productos;$('#admin-content').innerHTML=`<div class="admin-tabs"><button class="active">Productos (${response.productos.length})</button><button>Pedidos (${response.pedidos.length})</button></div><p class="form-note">Edita stock, precio, visibilidad y fotos desde aquí. Ocultar retira un producto sin borrarlo.</p><button class="button primary" data-admin-action="migrate">Pasar las fotos a Drive</button><table class="admin-table"><thead><tr><th>Foto</th><th>Producto</th><th>Precio</th><th>Stock</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>${response.productos.map(p=>`<tr data-admin-id="${p.id}"><td><img src="${imagePath(p)}" alt="" width="54" height="68" style="object-fit:cover;border-radius:4px"><input data-admin-image type="file" accept="image/jpeg,image/png,image/webp"></td><td><input data-field="nombre" value="${escapeHtml(p.nombre)}"></td><td><input data-field="precio" type="number" min="0" value="${Number(p.precio)||0}"></td><td><input data-field="stock" type="number" min="0" value="${Number(p.stock)||0}"></td><td><label><input data-field="visible" type="checkbox" ${p.visible!==false?'checked':''}> visible</label><label><input data-field="agotado_manual" type="checkbox" ${p.agotado_manual?'checked':''}> agotado</label></td><td><button class="button primary" data-admin-save>Guardar</button></td></tr>`).join('')}</tbody></table>`}
function readDataUrl(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)})}
async function uploadAdminImage(row,file){if(!file)return;if(file.size>4*1024*1024){showMessage('<h2>Imagen muy pesada</h2><p>La imagen debe pesar menos de 4 MB.</p>');return}const response=await send('image_upload',{token:state.adminToken,id:row.dataset.adminId,mime:file.type,data:await readDataUrl(file)});if(response.ok){showMessage('<h2>Foto actualizada</h2><p>La imagen ya quedó guardada en Drive.</p>');loadAdminData()}else showMessage(`<h2>No se subió</h2><p>${escapeHtml(response.message||'Revisa la conexión.')}</p>`)}
async function saveAdminProduct(row){const fields={};row.querySelectorAll('[data-field]').forEach(input=>{fields[input.dataset.field]=input.type==='checkbox'?input.checked:input.value});const response=await send('product_patch',{token:state.adminToken,id:row.dataset.adminId,...fields});if(response.ok){showMessage('<h2>Guardado</h2><p>El producto se actualizó correctamente.</p>')}else showMessage(`<h2>No se guardó</h2><p>${escapeHtml(response.message||'Revisa la conexión.')}</p>`)}
async function migrateImagesToDrive(){if(!isConnected){showMessage('<h2>Falta conectar Apps Script</h2><p>Primero coloca la URL terminada en /exec dentro de js/config.js.</p>');return}const products=state.adminProducts||[];let done=0;showMessage('<h2>Subiendo fotos...</h2><p>La ventana puede tardar unos minutos. No la cierres.</p>');for(const product of products){if(product.imagen_drive_id)continue;try{const response=await fetch('./'+product.imagen_repo);const blob=await response.blob();const result=await send('image_upload',{token:state.adminToken,id:product.id,mime:blob.type||'image/jpeg',data:await readDataUrl(blob)});if(result.ok)done++}catch(error){}}showMessage(`<h2>Fotos migradas</h2><p>${done} imágenes quedaron en Drive y vinculadas al catálogo.</p>`);loadAdminData()}
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
$('#open-cart').onclick=openCart;$('#cart-lines').onclick=handleCartClick;$('#order-form').onsubmit=submitOrder;document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>button.closest('dialog').close());$('#admin-root').onclick=event=>{if(event.target.dataset.adminAction==='logout'){state.adminToken='';localStorage.removeItem('fares-glam-admin-token');renderAdmin()}if(event.target.dataset.adminAction==='data')loadAdminData();if(event.target.dataset.adminAction==='migrate')migrateImagesToDrive();if(event.target.matches('[data-admin-save]'))saveAdminProduct(event.target.closest('[data-admin-id]'))};$('#admin-root').onchange=event=>{if(event.target.matches('[data-admin-image]'))uploadAdminImage(event.target.closest('[data-admin-id]'),event.target.files[0])};restoreCart();boot();
